inherit_from:
  - https://github.com/jgarber623/rubocop-configs/raw/main/.rubocop.yml
  - https://github.com/jgarber623/rubocop-configs/raw/main/.rubocop-rspec.yml

AllCops:
  Exclude:
    - bin/bundle
